test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,52 +7,36 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      workflow_id:
-        type: string 
-           
+     Workflow_ID:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7} 
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            echo "Destroying environment: << parameters.workflow_id >>} "
+            echo "Destroying environment: << parameters.workflow_id >> "
             aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}
-            aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
+            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
             aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7}
-  
-  notify_on_failure:
-      steps:
-        - slack/notify:
-            event: fail
-            channel: $SLACK_DEFAULT_CHANNEL
-            template: basic_fail_1
-  
-  notify_on_success:
-      steps:
-        - slack/notify:
-            event: pass
-            channel: $SLACK_DEFAULT_CHANNEL
-            template: success_tagged_deployment_1
-  
+
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      Workflow_ID:
-        type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}    
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
-          when: on_fail
+          # Add when this will run
           command: |
-            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
-            echo "$SUCCESS"
-            # Logic for reverting the database state
-            if (( $SUCCESS == 1 ));
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
             then
-              cd ~/project/backend
-              npm install
-              npm run migration:revert
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
             fi
             
 jobs:
@@ -177,6 +161,11 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
 
+      # Here's where you will add some code to rollback on failure      
+
+
+
+
   configure-infrastructure:
     docker:
       - image: yosefadel/aws-node
@@ -203,8 +192,8 @@ jobs:
             ls
             ansible-playbook -i inventory.txt configure-server.yml
 
-      - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+            
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
@@ -227,12 +216,9 @@ jobs:
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-                curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                curl https://kvdb.io/Kj46yPeom5ecCE1vbPLGX1/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-      - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations    
-           
+     # Here's where you will add some code to rollback on failure      
 
 
   deploy-frontend:
@@ -260,10 +246,7 @@ jobs:
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
-
+      # Here's where you will add some code to rollback on failure      
   deploy-backend:
     docker:
       - image: yosefadel/aws-node
@@ -298,9 +281,7 @@ jobs:
             ls ../.circleci/ansible/roles/deploy/
             cd ../.circleci/ansible
             ansible-playbook -i inventory.txt deploy-backend.yml
-      - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
+      # Here's where you will add some code to rollback on failure  
 
 
 
@@ -342,9 +323,7 @@ jobs:
             else
               exit 1
             fi
-      - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
-      - revert-migrations
+      # Here's where you will add some code to rollback on failure  
 
 
 
